added github icon to mobile version
worknenjoy/airspace-jekyll pull request #16
Opened 2020-01-28 01:03 UTC by meduardasf

Solved the problem where the GitHub badge was overlapping the menu button. 
Now, when the mobile version is accessed, the badge is replaced by an icon on the top right side of the page.

2020-01-28 13:48 UTC, alexanmtz requested changes

2020-01-28 13:48 UTC, alexanmtz commented on _site/index.html
> +    <a href="https://github.com/worknenjoy/airspace-jekyll/"> <img class="hidden-lg hidden-md hidden-sm" style="position: absolute; top: 40px; right: 10px; z-index:9999;" alt="Fork me on GitHub" src=
@meduardasf you did the changes on the generated file, not the source file

2020-01-28 19:30 UTC, meduardasf commented
Changes added in the source file

2020-01-29 19:52 UTC, alexanmtz approved these changes

2020-01-29 19:52 UTC, merged